### ISSUE TITLE
custom headers does not work

### ISSUE THREAD

**Issue by harris-chiu** [oplatek/csv2json#3]
Hi,

I notice that there's a bug in the code that the custom_headers doesn't pass along

When calling the convert function, change in the convert custom_headers to fieldnames would resolve the issue.

**Comment by oplatek** [comment]
Hi, thank you for reporting it. Will have a look at it today or tomorrow

**Comment by oplatek** [comment]
@harris-chiu IMO I fixed with the last PR. Feel free to reopen it if needed.

Thank you for your patience
