### ISSUE TITLE
Unable to handle tsv file format

### ISSUE THREAD

**Issue by aswathkk** [oplatek/csv2json#6]
The `--csv_delimiter` flag doesn't accepts `\t`

When I modified source like this:
```
p.add_argument('--csv_delimiter', default='\t')
```
It is able to handle tab separated files. Need to do something wrt `--csv_delimiter` flag.

**Comment by oplatek** [comment]
Use `./csv-to-json --csv_delimiter $'\t' test_tab.csv `
See https://superuser.com/questions/362235/how-do-i-enter-a-literal-tab-character-in-a-bash-shell
